name: toss_invest_api
description: "Unofficial Dart package for Toss Invest Open API with REST API and WebSocket support."
version: 0.1.0-dev.5

homepage: https://github.com/dekay3388/toss_invest_api
repository: https://github.com/dekay3388/toss_invest_api
issue_tracker: https://github.com/dekay3388/toss_invest_api/issues

topics:
  - toss
  - toss-invest
  - toss-invest-api
  - toss-invest-open-api

environment:
  sdk: ^3.13.0

dependencies:
  http: ^1.6.0
  web_socket_channel: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  test: ^1.32.0
  lints: ^6.1.0
  build_runner: ^2.16.0
  freezed: ^4.0.0
  json_serializable: ^6.14.0
